import { ClientAuthContextProvider } from "@/context/ClientAuthContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }: { children: React.ReactNode }) {
  return (
      <main>
        <ClientAuthContextProvider>{children}</ClientAuthContextProvider>
      </main>
  );
}
